In [16]:
import numpy as np

v = np.array([[1],
              [2],
              [3],
              [4],
              [5]])
print("v: \n", v, "\n")

u = np.exp(v)
print("u: \n", u, "\n")

print("log v: \n", np.log(v), "\n")
print("abs v: \n", np.abs(v), "\n")
print("max v: \n", np.maximum(v, 0), "\n")
print("v**2: \n", v**2,"\n")
print("square v: \n", np.square(v), "\n")
print("1/v: \n", (1/v),  "\n")
print("reciprocal v: ", np.reciprocal(v), "\n")

v: 
 [[1]
 [2]
 [3]
 [4]
 [5]] 

u: 
 [[  2.71828183]
 [  7.3890561 ]
 [ 20.08553692]
 [ 54.59815003]
 [148.4131591 ]] 

log v: 
 [[0.        ]
 [0.69314718]
 [1.09861229]
 [1.38629436]
 [1.60943791]] 

abs v: 
 [[1]
 [2]
 [3]
 [4]
 [5]] 

max v: 
 [[1]
 [2]
 [3]
 [4]
 [5]] 

v**2: 
 [[ 1]
 [ 4]
 [ 9]
 [16]
 [25]] 

square v: 
 [[ 1]
 [ 4]
 [ 9]
 [16]
 [25]] 

1/v: 
 [[1.        ]
 [0.5       ]
 [0.33333333]
 [0.25      ]
 [0.2       ]] 

reciprocal v:  [[1]
 [0]
 [0]
 [0]
 [0]] 

